### PR TITLE
[PR] Adding badges to README

### PR DESCRIPTION
**Pull request by LuchoTurtle**
This is a micro-PR just to check if Codecov is properly working in PRs

### CODE REVIEW

**Comment by LuchoTurtle** [comment]
Looks good.
Merging to add a few badges and finish #1 .

**Comment by nelsonic** [comment]
Is there a badge for CI? e.g: GitHub Workflow Status
```md
![GitHub Workflow Status](https://img.shields.io/github/workflow/status/dwyl/dart_multihash/Build?label=build&style=flat-square&branch=main)
```

**Comment by LuchoTurtle** [comment]
It's already added 
image

**Comment by nelsonic** [comment]
_Strong_ pref for the `flat-square` badges for consistency with our other repos. 💭 
But this is already _much_ better than a "bare" repo. 👍

**Pull request merged**
